name: AI PR Review
description: "Reviews pull requests using AI based on a rules file."

inputs:
  repository:
    description: "The repository name (owner/repo)"
    required: true
  pr_number:
    description: "The pull request number"
    required: true
  commit_id:
    description: "The commit SHA"
    required: true
  github_token:
    description: "GitHub token for authentication"
    required: true
  ai_provider:
    description: "AI provider to use (openai, anthropic)"
    required: false
    default: "openai"
  ai_api_key:
    description: "API key for the selected AI provider"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install openai anthropic requests unidiff
      shell: bash

    - name: Run AI Reviewer
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        AI_PROVIDER: ${{ inputs.ai_provider }}
        AI_API_KEY: ${{ inputs.ai_api_key }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
        PR_NUMBER: ${{ inputs.pr_number }}
        COMMIT_ID: ${{ inputs.commit_id }}
      run: python "${{ github.action_path }}/main.py"
